config/routes.rb
Rails.application.routes.draw do

  get 'group_email_comments/index'
  get 'group_email_comments/edit'
  devise_scope :voter do
    constraints -> request { request.session[:admin].present? || request.session[:voter_id].present? } do
      root 'voterposts#index', as: :voter_root, constraints: LoggedInConstraint.new("voter") # 投票者としてログインしている場合
      root 'staffs/staffs#toppage', as: :wip_root, constraints: LoggedInConstraint.new("true") # WIPとしてログインしている場合
      root 'staffs/staffs#toppage', as: :other_root, constraints: LoggedInConstraint.new("false") # スポンサー企業としてログインしている場合
    end
    root "voters/registrations#new", as: :public_root
  end

  devise_for :voters, :controllers => {
    :registrations => 'voters/registrations',
    :sessions => 'voters/sessions'
  }

  devise_for :staffs, :controllers => {
    :registrations => 'staffs/registrations',
    :sessions => 'staffs/sessions'
  }

  # 川柳投稿者
  resources :users, only: [:create, :index] do
    collection do
      post :confirm
      get :thanks
    end
  end
  # resources :posts
  
  # 川柳投票
  resources :voterposts do
    resource :likes, only: [:create, :destroy]
  end

  # 管理者・スタッフページ
  namespace :staffs do
    get 'staffs/toppage', to: 'staffs#toppage'
    get 'staffs/index', to: 'staffs#index'
    get 'staffs/users_index', to: 'staffs#users_index'
    get 'staffs/users_graph', to: 'staffs#users_graph'
    get 'staffs/users_show', to: 'staffs#users_show'
    get 'staffs/voterposts_index', to: 'staffs#voterposts_index'
    get 'staffs/voterposts_show', to: 'staffs#voterposts_show'
    post 'staffs/voterposts_index/import', to: 'staffs#import'
    get 'staffs/group_index', to: 'staffs#group_index'
  end

  # adminmessageメール内容変更
  resources :adminmessages
  # 一斉メール  
  resources :group_email_comments do
    member do
      get 'group_email'
    end
  end   
    
  # health_check
  namespace :alb do
    get 'health_check'
  end
end

app/models/group_email_comment.rb
class GroupEmailComment < ApplicationRecord
  belongs_to :staff

  validates :subject, presence: true
  validates :comment, presence: true
end

app/controllers/group_email_comments_controller.rb
class GroupEmailCommentsController < ApplicationController
  before_action :group_email_create, only: [:index]

  def index
    @staff = Staff.find(params[:id])
    @group_email_comments = @staff.group_email_comments.all
    @group_email_comment = @staff.group_email_comments.find_by(staff_id: params[:id])
  end

  def edit
    @group_email_comment = GroupEmailComment.find(params[:id])
  end

  def update
    @group_email_comment = GroupEmailComment.find(params[:id])
    if @group_email_comment.update(group_email_comment_params)
      flash[:success] = "更新しました。"
      redirect_to group_email_comments_path(id: current_staff.id)
    else
      render :index
    end
  end

  # def destroy
  #   @group_email_comment = GroupEmailComment.find(params[:id])
  #   @group_email_comment.destroy
  #   flash[:success] = "データを削除しました。"
  #   redirect_to group_email_comments_path(id: current_staff.id)
  # end

  def group_email
    @group_email_comment = GroupEmailComment.find_by(staff_id: params[:id])
    @group_email_comments = GroupEmailComment.all
    GroupMailer.send_announcement_mail(@group_email_comment.subject, @group_email_comment.comment, User.all.pluck(:email))
               .deliver_now
    flash[:success] = 'メールを一斉送信しました。'
    redirect_to group_email_comments_path(id: current_staff.id)
  end

  private

  def group_email_comment_params
    params.require(:group_email_comment).permit(:subject, :comment, :staff_id)
  end

  def group_email_create
    @staff = Staff.find(params[:id])
    @group_email_comments = @staff.group_email_comments.all
    @group_email_comment = @staff.group_email_comments.find_by(staff_id: params[:id])
    return if @group_email_comments.present?

    @group_email_comment = @staff.group_email_comments.create!(subject: "題test", comment: "テスト内容", staff_id: current_staff.id)
  end
end

app/helpers/group_email_comments_helper.rb
module GroupEmailCommentsHelper
end

app/views/group_email_comments/_edit.html.erb
<% provide(:class_text, 'edit-message') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
    <h2 class="modal-title modal-title-group-email-edit">一斉メール編集</h2>
      <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close">
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="group-email-modal col-md-12 col-md-offset-4">
          <%= form_with(model: @group_email_comment, local: true, method: :patch) do |f| %>
            <%# <%= render 'shared/error_messages', object: @user  %>
            <%= f.hidden_field :staff_id, value: current_staff.id %>
            <%= f.label "件名", class: 'form-label' %>
            <%= f.text_field :subject, class: "form-control mb-4"%>
            <%= f.label "メール内容", class: 'form-label' %>
            <%= f.text_area :comment, size: "25x10", class: "form-control form-size"%>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/group_email_comments/edit.js.erb
$("#edit-group-email-comment").html("<%= escape_javascript(render 'edit') %>");
$("#edit-group-email-comment").modal("show");

app/views/group_email_comments/index.html.erb
<div class="group_email-body">
  <h1>メール一斉送信<h1>

  <div class="col-mw-md col-mw-xl center-block">
    <p class="tyui">※下記の内容を確認後メール一斉送信のボタンをクリックしてください。</p>
      
    <div class="group-email-comment-index-table mw-md col-mw-xl center-block">
      <table class="table table-sm">
        <tr>
          <th class="group-email-comment-index-table-th">一斉メール内容</th>
        </tr>  
        <% if @group_email_comments.present? %>
          <% @group_email_comments.each do |group| %>
            <tr>
              <td class="group-email-comment-index-table-td">
                件名：<%= group.subject %>
              </td>
              </tr>
            <tr>
              <td class="group-email-comment-index-table-td">
                <%= simple_format(group.comment) %>
              </td>
              </tr>
              <tr>
              <td class="group-email-comment-index-table-td">
                <%= link_to "編集", edit_group_email_comment_path(id: group.id, staff_id: current_staff.id), remote: true, class: "btn btn-success" %> 
                <%# <%= link_to "削除", group, method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" <br> %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
    <div class="group-email-comment-btn">
      <%= link_to "メール一斉送信", group_email_group_email_comment_path(id: current_staff.id), data: { confirm: "応募者全員にメールを送信します。よろしいですか？" }, class: "btn btn-primary btn-form" %>
    </div>
    <div class="group-email-comment-btn">
      <%= link_to "部門選択画面へ戻る", staffs_staffs_toppage_path(format: current_staff.id), class: "btn-gradient confirm-btn" %>
    </div>
  </div>
  <!--モーダルウインドウ表示-->
  <div id="edit-group-email-comment" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
</div>