config/routes.rb
Rails.application.routes.draw do

  get 'group_email_comments/index'
  get 'group_email_comments/edit'
  devise_scope :voter do
    constraints -> request { request.session[:admin].present? || request.session[:voter_id].present? } do
      root 'voterposts#index', as: :voter_root, constraints: LoggedInConstraint.new("voter") # 投票者としてログインしている場合
      root 'staffs/staffs#toppage', as: :wip_root, constraints: LoggedInConstraint.new("true") # WIPとしてログインしている場合
      root 'staffs/staffs#toppage', as: :other_root, constraints: LoggedInConstraint.new("false") # スポンサー企業としてログインしている場合
    end
    root "voters/registrations#new", as: :public_root
  end

  devise_for :voters, :controllers => {
    :registrations => 'voters/registrations',
    :sessions => 'voters/sessions'
  }

  devise_for :staffs, :controllers => {
    :registrations => 'staffs/registrations',
    :sessions => 'staffs/sessions'
  }

  # 川柳投稿者
  resources :users, only: [:create, :index] do
    collection do
      post :confirm
      get :thanks
    end
  end
  # resources :posts
  
  # 川柳投票
  resources :voterposts do
    resource :likes, only: [:create, :destroy]
  end

  # 管理者・スタッフページ
  namespace :staffs do
    get 'staffs/toppage', to: 'staffs#toppage'
    get 'staffs/index', to: 'staffs#index'
    get 'staffs/users_index', to: 'staffs#users_index'
    get 'staffs/users_graph', to: 'staffs#users_graph'
    get 'staffs/users_show', to: 'staffs#users_show'
    get 'staffs/voterposts_index', to: 'staffs#voterposts_index'
    get 'staffs/voterposts_show', to: 'staffs#voterposts_show'
    post 'staffs/voterposts_index/import', to: 'staffs#import'
    get 'staffs/group_index', to: 'staffs#group_index'
  end

  # adminmessageメール内容変更
  resources :adminmessages
  # 一斉メール  
  resources :group_email_comments do
    member do
      get 'group_email'
    end
  end   
    
  # health_check
  namespace :alb do
    get 'health_check'
  end
end

app/models/adminmessage.rb
class Adminmessage < ApplicationRecord
  belongs_to :staff
end

app/controllers/adminmessages_controller.rb
class AdminmessagesController < ApplicationController
  def index
    @message = Adminmessage.new
    @messages = Adminmessage.all
  end

  def create
    @message = Adminmessage.new(message_params)
    if @message.save
      flash[:success] = 'メール内容を新規登録しました。'
      redirect_to adminmessages_path(id: current_staff.id)
    else
      render :index
      flash[:success] = 'メール内容の登録に失敗しました。'
    end
  end

  def edit
    @message = Adminmessage.find(params[:id])
  end

  def update
    @message = Adminmessage.find(params[:id])
    if @message.update(message_update_params)
      flash[:success] = "メール内容を更新しました。"
      redirect_to adminmessages_path(id: current_staff.id)
    else
      render :index
    end
  end

  def destroy
    @message = Adminmessage.find(params[:id])
    @message.destroy
    flash[:success] = "データを削除しました。"
    redirect_to adminmessages_path(id: current_staff.id)
  end

  private

  def message_params
    params.permit(:message, :staff_id)
  end

  def message_update_params
    params.require(:adminmessage).permit(:message, :staff_id)
  end
end

app/helpers/adminmessages_helper.rb
module AdminmessagesHelper
end

app/views/adminmessages/_edit.html.erb
<%# <h1>editページ</h1> %>
<% provide(:class_text, 'edit-message') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
    <h2 class="modal-title">編集</h2>
      <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close">
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 col-md-offset-4">
          <%= form_with(model: @message, local: true, method: :patch) do |f| %>
            <%# <%= render 'shared/error_messages', object: @user  %>
            <%= f.hidden_field :staff_id, value: current_staff.id %>
            <%= f.label "メール内容", class: 'form-label' %>
            <%= f.text_area :message, size: "25x15", class: "form-control form-size"%>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/adminmessages/edit.js.erb
$("#edit-adminmessage").html("<%= escape_javascript(render 'edit') %>");
$("#edit-adminmessage").modal("show");

app/views/adminmessages/index.html.erb

<div class="adminmessage-body col-mw-md col-mw-xl center-block">
  <h1>投句完了メール<h1>

  <div>
    <%= form_with(model: @adminmessage, local: true) do |f| %>
      <%= f.hidden_field :staff_id, value: params[:id] %>
      <% f.label "メール内容" %>
      <%= f.text_area :message, size: "25x8", class: "form-control form-size"%>
      <%= f.submit "新規メール内容登録", class: "btn btn-primary  btn-form" %>
    <% end %>
  </div>
  <p class="tyui">※複数登録できますが、メールに載りますので、必要のないメッセージは削除してください。</p>
  <div class="adminmessage-index-table mw-md col-mw-xl center-block">
    <table class="table table-sm">
      <tr>
        <th class="adminmessage-index-table-th">メール内容</th>
      </tr>  
      <% if @messages.present? %>
        <% @messages.each do |message| %>
          <tr>
            <td class="adminmessage-index-table-td">
              <%= simple_format(message.message) %>
            </td>
            </tr>
            <tr>
            <td class="adminmessage-index-table-td">
              <%= link_to "編集", edit_adminmessage_path(id: message.id, staff_id: current_staff.id), remote: true, class: "btn btn-success" %> 
              <%= link_to "削除", message, method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %><br>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>

  <div class="adminmessage-btn">
    <%= link_to "部門選択画面へ戻る", staffs_staffs_toppage_path(format: current_staff.id), class: "btn-gradient confirm-btn" %>
  </div>
</div>
<!--モーダルウインドウ表示-->
<div id="edit-adminmessage" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>