config/routes.rb
Rails.application.routes.draw do

  get 'group_email_comments/index'
  get 'group_email_comments/edit'
  devise_scope :voter do
    constraints -> request { request.session[:admin].present? || request.session[:voter_id].present? } do
      root 'voterposts#index', as: :voter_root, constraints: LoggedInConstraint.new("voter") # 投票者としてログインしている場合
      root 'staffs/staffs#toppage', as: :wip_root, constraints: LoggedInConstraint.new("true") # WIPとしてログインしている場合
      root 'staffs/staffs#toppage', as: :other_root, constraints: LoggedInConstraint.new("false") # スポンサー企業としてログインしている場合
    end
    root "voters/registrations#new", as: :public_root
  end

  devise_for :voters, :controllers => {
    :registrations => 'voters/registrations',
    :sessions => 'voters/sessions'
  }

  devise_for :staffs, :controllers => {
    :registrations => 'staffs/registrations',
    :sessions => 'staffs/sessions'
  }

  # 川柳投稿者
  resources :users, only: [:create, :index] do
    collection do
      post :confirm
      get :thanks
    end
  end
  # resources :posts
  
  # 川柳投票
  resources :voterposts do
    resource :likes, only: [:create, :destroy]
  end

  # 管理者・スタッフページ
  namespace :staffs do
    get 'staffs/toppage', to: 'staffs#toppage'
    get 'staffs/index', to: 'staffs#index'
    get 'staffs/users_index', to: 'staffs#users_index'
    get 'staffs/users_graph', to: 'staffs#users_graph'
    get 'staffs/users_show', to: 'staffs#users_show'
    get 'staffs/voterposts_index', to: 'staffs#voterposts_index'
    get 'staffs/voterposts_show', to: 'staffs#voterposts_show'
    post 'staffs/voterposts_index/import', to: 'staffs#import'
    get 'staffs/group_index', to: 'staffs#group_index'
  end

  # adminmessageメール内容変更
  resources :adminmessages
  # 一斉メール  
  resources :group_email_comments do
    member do
      get 'group_email'
    end
  end   
    
  # health_check
  namespace :alb do
    get 'health_check'
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login_id]

  has_many :adminmessages, dependent: :destroy
  has_many :group_email_comments, dependent: :destroy

  validates :login_id, presence: true, length: { is: 8 }

  # 登録時にメールアドレスを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

  # importメソッド
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      staff = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      staff.attributes = row.to_hash.slice(*updatable_attributes)
      staff.save!
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    %w[login_id group_name password password_confirmation]
  end
end

app/controllers/staffs/confirmations_controller.rb
# frozen_string_literal: true

class Staffs::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/staffs/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Staffs::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/staffs/passwords_controller.rb
# frozen_string_literal: true

class Staffs::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/staffs/registrations_controller.rb
# frozen_string_literal: true

class Staffs::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staffs/sessions_controller.rb
# frozen_string_literal: true

class Staffs::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def create
    return unless params[:staff]['login_id'].present?

    # login_idだけでログインできるように変更
    self.resource = Staff.where(login_id: params[:staff]['login_id']).first
    if resource.present?
      set_flash_message(:notice, :signed_in) if is_flashing_format?
      sign_in(resource_name, resource)
      yield resource if block_given?

      case resource.admin
      when "true"
        session[:admin] = "true"
      when "false"
        session[:admin] = "false"
      end
      respond_with resource, location: after_sign_in_path_for(resource)
    else
      flash[:danger] = "登録された名前が違います"
      redirect_to new_staff_session_path
    end
  end

  # ログイン後の画面遷移
  def after_sign_in_path_for(resource)
    staffs_staffs_toppage_path(resource)
  end

  # ログアウト後の画面遷移
  def after_sign_out_path_for(_resource)
    new_staff_session_path
  end
end

app/controllers/staffs/staffs_controller.rb
require 'csv'
require 'nkf'

class Staffs::StaffsController < ApplicationController
  before_action :staff_only
  before_action :correct_staff
  before_action :detect_device, only: [:voterposts_show]

  def toppage
  end

  def index
    # 投票者別ランキング
    @post_like = Post.find(Like.where(voter_id: Voter.where(group: params[:group_name]).ids)
                     .group(:post_id).order(Arel.sql('count(post_id) desc')).pluck(:post_id))

    # カテゴリー別に表示
    @post_rank = @post_like.select { |post| post.category == params[:category_name] }.paginate(page: params[:page], per_page: 100)
    @posts_index = Post.eager_load(:user).where(category: params[:category_name]).paginate(page: params[:page], per_page: 100)
    @staffs = Staff.where(admin: false)
    @staff = Staff.find_by(group_name: params[:group_name])
    @users = User.eager_load(:posts).all
    @posts = Post.all.where.not(first_phrase: "")
    @voters = Voter.eager_load(:voterposts).all
    @voterposts = Voterpost.all.order(voter_id: "ASC")

    case params[:key]
    when "posts"
      send_posts_csv(@posts)
    when "users"
      send_users_csv(@users)
    when "voters"
      send_voters_csv(@voterposts)
    end
  end

  # 川柳csv出力
  def send_posts_csv(posts)
    bom = "\uFEFF"
    csv_data = if current_staff.admin
                 CSV.generate(bom) do |csv|
                   header = %w[No 上の句 中の句 下の句 ペンネーム 部門 氏名 Email 性別 お住まい 職業 年代 メッセージ アンケート 得票数（WIP） 得票数（全体）]
                   csv << header

                   posts.each do |post|
                     user = User.find_by(id: post.user_id)
                     count_votes_for_wip = Like.where(voter_id: Voter.where(group: params[:group_name]).ids)
                                               .where(post_id: post.id).count
                     count_votes_for_all = Like.where(post_id: post.id).count
                     values = posts_csv_values_for_admin(post, user, count_votes_for_wip, count_votes_for_all)
                     csv << values
                   end
                 end
               else
                 CSV.generate(bom) do |csv|
                   header = %w[No 上の句 中の句 下の句 ペンネーム 部門 性別 お住まい 職業 年代 メッセージ アンケート 得票数]
                   csv << header

                   posts.each do |post|
                     user = User.find_by(id: post.user_id)
                     count_votes_for_other = Like.where(voter_id: Voter.where(group: params[:group_name]).ids)
                                                 .where(post_id: post.id).count
                     values = posts_csv_values_for_other(post, user, count_votes_for_other)
                     csv << values
                   end
                 end
               end
    send_data(csv_data, filename: "jokatsu_senryu.csv")
  end

  # 投稿者csv出力
  def send_users_csv(users)
    bom = "\uFEFF"
    csv_data = CSV.generate(bom) do |csv|
      header = %w[No 氏名 Email 性別 お住まい 職業 （職業：その他） 年代 メッセージ アンケート]
      csv << header

      users.each do |user|
        name = user.name.gsub(/[[:space:]]/, '').strip.tr('０-９ａ-ｚＡ-Ｚ', '0-9a-zA-Z')
        name = NKF.nkf('-w -Z1', name)
        values = users_csv_values(user, name)
        csv << values
      end
    end
    send_data(csv_data, filename: "jokatsu_senryu_users.csv")
  end

  # 一押し川柳csv出力
  def send_voters_csv(voterposts)
    bom = "\uFEFF"
    csv_data = CSV.generate(bom) do |csv|
      header = %w[氏名 グループ No1川柳（女性パワーで未来を変えるの部） 推薦理由（女性パワーで未来を変えるの部）
                  No1川柳（ジェンダー・多様性の部） 推薦理由（ジェンダー・多様性の部） No1川柳（はたらく女子の部） 推薦理由（はたらく女子の部）
                  No1川柳（ママ・子どもの部） 推薦理由（ママ・子どもの部） No1川柳（名もなき家事の部） 推薦理由（名もなき家事の部）
                  No1川柳（本当にありがとう❣️感謝の部） 推薦理由（本当にありがとう❣️感謝の部） No1川柳（あるある❣️の部） 推薦理由（あるある❣️の部）
                  No1川柳（涙がポロ❣️の部） 推薦理由（涙がポロ❣️の部） No1川柳（輝け❣️私のライフスタイルの部） 推薦理由（輝け❣️私のライフスタイルの部）
                  No1川柳（心がきゅん❣️私の癒しの部） 推薦理由（心がきゅん❣️私の癒しの部） No1川柳（SDGsアクションの部） 推薦理由（SDGsアクションの部）]
      csv << header
      # if current_staff.admin
      voterposts.each do |voterpost|
        voter = Voter.find(voterpost.voter_id)
        values = voters_csv_values(voter, voterpost)
        csv << values
      end
      # 管理者以外は投票者csvをダウンロードする必要がないとのことでコメントアウト
      # else
      #   voter_ids = Voter.where(id: voterposts.select(:voter_id)).where(group: params[:group_name]).ids
      #   voter_ids.each do |voter_id|
      #     voter = Voter.find(voter_id)
      #     voterpost = voterposts.find_by(voter_id: voter_id)
      #     values = voters_csv_values(voter, voterpost)
      #     csv << values
      #   end
      # end
    end
    send_data(csv_data, filename: "jokatsu_senryu_voters.csv")
  end

  def users_index
    @search_params = user_search_params
    @users = User.search(@search_params).paginate(page: params[:page], per_page: 50)
    # @users_count = User.distinct.count(:name)
    @users_count = User.count('DISTINCT name')
  end

  def users_show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end

  def voterposts_index
    @voters_admin = Voter.all.order(:group)
    @voters = Voter.where(group: current_staff.group_name)
  end

  def users_graph
  end

  def voterposts_show
    @voter = Voter.find(params[:id])
    @voterpost = Voterpost.find_by(voter_id: @voter.id)
  end

  def import
    if params[:file].blank?
      flash[:danger] = "csvファイルが選択されていません。"
    else
      # fileはtmpに自動で一時保存される
      Staff.import(params[:file])
      flash[:success] = "CSVファイルをインポートしました。"
    end
    redirect_to staffs_staffs_voterposts_index_url
  end

  def group_index
    @staffs = Staff.all
    @group_members = Voter.all
  end

  private

  def user_search_params
    params.fetch(:search, {}).permit(:name)
  end

  def detect_device
    case request.user_agent
    when /iPhone/, /Android/
      request.variant = :mobile
    end
  end

  # 川柳csvの管理者ダウンロード時の値
  def posts_csv_values_for_admin(post, user, count_votes_for_wip, count_votes_for_all)
    [
      post.id, post.first_phrase, post.second_phrase, post.third_phrase, post.pen_name, post.category,
      user.name, user.email, user.gender, user.address, user.profession, user.age, user.note, user.questionary,
      count_votes_for_wip, count_votes_for_all
    ]
  end

  # 川柳csvの管理者以外のダウンロード時の値
  def posts_csv_values_for_other(post, user, count_votes_for_other)
    [
      post.id, post.first_phrase, post.second_phrase, post.third_phrase, post.pen_name, post.category,
      user.gender, user.address, user.profession, user.age, user.note, user.questionary,
      count_votes_for_other
    ]
  end

  # 投稿者csvダウンロード時の値
  def users_csv_values(user, name)
    [
      user.id, name, user.email, user.gender, user.address, user.profession,
      user.other, user.age, user.note, user.questionary
    ]
  end

  # 一押し川柳csvダウンロード時の値
  def voters_csv_values(voter, voterpost)
    [
      voter.name, voter.group, voterpost.favorite_post1, voterpost.reason1, voterpost.favorite_post2,
      voterpost.reason2, voterpost.favorite_post3, voterpost.reason3, voterpost.favorite_post4,
      voterpost.reason4, voterpost.favorite_post5, voterpost.reason5, voterpost.favorite_post6,
      voterpost.reason6, voterpost.favorite_post7, voterpost.reason7, voterpost.favorite_post8,
      voterpost.reason8, voterpost.favorite_post9, voterpost.reason9, voterpost.favorite_post10,
      voterpost.reason10, voterpost.favorite_post11, voterpost.reason11, voterpost.favorite_post9,
      voterpost.reason9, voterpost.favorite_post10, voterpost.reason10, voterpost.favorite_post11, voterpost.reason11
    ]
  end
end

app/controllers/staffs/unlocks_controller.rb
# frozen_string_literal: true

class Staffs::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/staffs/_result_posts.html.erb
<div class="result-posts">
  <% if params[:admin] == "true" %>
    <%= link_to "WIPの画面へ戻る", staffs_staffs_index_path(group_name: current_staff.group_name, category_name: params[:category_name]), class: "btn-gradient confirm-btn mb-3" %>
  <% end %>
  <div class="mb-2">
    <%= will_paginate(@post_rank, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div> 
  <% @post_rank.each do |post| %>
    <% if post.first_phrase.present? && post.category == params[:category_name] %>
      <div class="main-index d-flex border-bottom mb-2">
        【得票数：<%= Like.where(post_id: post.id).where(voter_id: Voter.where(group: params[:group_name]).ids).count %> 】
        <%= post.id %>.　<%= post.first_phrase %>　<%= post.second_phrase %>　<%= post.third_phrase %> /(<%= post.pen_name %>)
        /<%= post.user.gender %>/<%= post.user.address %>/<%= post.user.profession %>/<%= post.user.age %>/<%= post.user.note %>
        <% if params[:admin] == "true" %>
          【名前：<%= post.user.name %> / Eメール：<%= post.user.email %>】
        <% end %>  
        <br>
      </div>  
    <% end %>
  <% end %>
  <%
=begin%>
  <hr>
 <% @posts_index.each do |post| %>
    <% if post.first_phrase.present? && post.category == params[:category_name] %>
      <div class="main-index d-flex border-bottom mb-2">
        【得票数：<%= Like.where(post_id: post.id).where(voter_id: Voter.where(group: params[:group_name]).ids).count %> 】
        <%= post.id %>.　<%= post.first_phrase %>　<%= post.second_phrase %>　<%= post.third_phrase %> /(<%= post.pen_name %>)
        /<%= post.user.gender %>/<%= post.user.address %>/<%= post.user.profession %>/<%= post.user.age %>
        <% if params[:admin] == "true" %>
          【名前：<%= post.user.name %> / Eメール：<%= post.user.email %>】
        <% end %>  
        <br>
      </div>  
    <% end %>
  <% end %> 
<%
=end%>
  <% if params[:admin] == "true" %>
    <%= link_to "WIPの画面へ戻る", staffs_staffs_index_path(group_name: current_staff.group_name, category_name: params[:category_name]), class: "btn-gradient confirm-btn mt-3" %>
  <% end %>   
</div>

app/views/staffs/staffs/group_index.js.erb
$("#group-index").html("<%= escape_javascript(render 'group_index') %>");
$("#group-index").modal("show");

app/views/staffs/staffs/index.html.erb
<div class="col-mw-md col-mw-xl center-block staff-index">
  <h1><%= params[:group_name] %> の投票結果</h1>
  <h3 class="mt-5">部門：<%= params[:category_name] %></h3>
  <h3 class="mb-3">投稿数：<%= Post.where(category: params[:category_name]).count %>句</h3>
  <% if params[:group_name] == "WIP" %>
    <div class="group-btn mb-4">
      <% @staffs.each do |staff| %>
        <%= link_to "#{staff.group_name}", staffs_staffs_index_path(group_name: staff.group_name, category_name: params[:category_name], admin: current_staff.admin), class: "btn btn-primary" %>
      <% end %>  
    </div>
    <div class="mb-3">
      <%= will_paginate(@post_rank, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
    </div>
    <div class="result-posts">
      <% @post_rank.each do |post| %>
        <% if post.first_phrase.present? && post.category == params[:category_name] %>
          <div class="main-index d-flex border-bottom mb-2">
            【得票数：<%= Like.where(post_id: post.id).where(voter_id: Voter.where(group: params[:group_name]).ids).count %> 】
            <%= post.id %>.　<%= post.first_phrase %>　<%= post.second_phrase %>　<%= post.third_phrase %> /(<%= post.pen_name %>)
            /<%= post.user.gender %>/<%= post.user.address %>/<%= post.user.profession %>/<%= post.user.age %>/<%= post.user.note %>
            【名前：<%= post.user.name %> / Eメール：<%= post.user.email %>】<br>
          </div>
        <% end %>
      <% end %>
    </div>
<%
=begin%>
    <hr>
 <div class="result-posts">
      <% @posts_index.each do |post| %>
        <% if post.first_phrase.present? && post.category == params[:category_name] %>
          <div class="main-index d-flex border-bottom mb-2">
            【得票数：<%= Like.where(post_id: post.id).where(voter_id: Voter.where(group: params[:group_name]).ids).count %> 】
            <%= post.id %>.　<%= post.first_phrase %>　<%= post.second_phrase %>　<%= post.third_phrase %> /(<%= post.pen_name %>)
            /<%= post.user.gender %>/<%= post.user.address %>/<%= post.user.profession %>/<%= post.user.age %>【名前：<%= post.user.name %> / Eメール：<%= post.user.email %>】<br>
          </div>
        <% end %>
      <% end %>
    </div> 
<%
=end%>
  <% elsif params[:group_name] == @staff.group_name %>
    <%= render "result_posts" %>
  <% end %>
  <div class="pagenate">
    <%= will_paginate(@post_rank, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div> 
  <%= link_to "部門選択画面へ戻る", staffs_staffs_toppage_path(format: current_staff.id), class: "btn-gradient confirm-btn mt-2" %>
</div>

app/views/staffs/staffs/users_index.html.erb
<div class="container mt-2 col-md-10 col-lg-8 users-index">
      <h1>投稿者一覧</h1>

  <form class="inline">
    <div class="users-count inline">
      <p class="mt-3">投稿者数：<%= @users_count %>名 /</p>&nbsp;
      <p class="mt-3">延べ投稿者数：<%= @users.count %>名</p>&nbsp;
      <p><%= link_to "グラフへ", staffs_staffs_users_graph_path, class: "btn-gradient-radius" %></p>
    </div>  
    <div class="search-form inline mt-3">
      <%= form_with(scope: :search, url: staffs_staffs_users_index_path, method: :get, local: true) do |f| %>
        <div class="mx-sm-1 mb-2">
          <%= f.text_field :name, value: @search_params[:name], placeholder: "名前で検索", class: "form-control" %>
        </div>
        <%= f.submit t('helpers.submit.search'), class: "btn btn-primary mb-3 ms-xs-1" %>
      <% end %>
    </div>
  </form>
  <div class="row mt-3">
    <div class="col-4 col-lg-4 mb-1">
      名前
    </div>
    <div class="col-6 col-lg-6 mb-1">
      Eメール
    </div>
    <div class="col-2">
    </div>
  </div>
  <% @users.each_with_index do |user| %>
    <div class="row">
      <div class="d-flex align-items-center border-top users-index col-4 col-lg-4">
        <%= user.name %>
      </div>
      <div class="d-flex align-items-center border-top users-index col-6 col-lg-6">
        <%= user.email %>
      </div>
      <div class="d-flex align-items-center border-top users-index col-2">
        <%= link_to "詳細", staffs_staffs_users_show_path(id: user.id), class: "btn btn-dark mb-2 btn-sm" %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="d-flex border-top col-12 pagenate">
      <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
    </div>  
  </div>
  <% if params[:search].present? %>
    <%= link_to "一覧へ戻る", staffs_staffs_users_index_path, class: "btn-gradient confirm-btn mt-2" %>
  <% else %>
    <%= link_to "戻る", staffs_staffs_toppage_path, class: "btn-gradient confirm-btn mt-2" %>
  <% end %>  
</div>

app/views/staffs/staffs/voterposts_index.html.erb
<div class="container mt-2 col-md-10 col-lg-8 users-index">
  <h1 class="mb-4">投票者・グループ一覧</h1>
  <% if current_staff.admin? %>
    <div class="staff_import">
      <%= form_with url: staffs_staffs_voterposts_index_import_path, multipart: true, local: true do |f| %>
        <%= f.file_field :file, class: "file_field" %>
        <%= f.submit "CSVをインポート", class: "btn btn-primary btn-sm mb-3" %>
      <% end %>
      <div class="group_index ms-4">
        <%= link_to "グループ一覧", staffs_staffs_group_index_path, remote: true, class: "btn-gradient-radius" %>
      </div>  
    </div>
    <div class="row mt-3">
      <div class="col-4 col-lg-4 mb-1">
        名前
      </div>
      <div class="col-6 col-lg-6 mb-1">
        グループ
      </div>
      <div class="col-2">
      </div>
    </div>
    <% @voters_admin.each do |voter| %>
      <div class="row">
        <div class="d-flex align-items-center border-top users-index col-4 col-lg-4">
          <%= voter.name %>
        </div>
        <div class="d-flex align-items-center border-top users-index col-6 col-lg-6">
          <%= voter.group %>
        </div>
        <div class="d-flex align-items-center border-top users-index col-2">
          <%= link_to "詳細", staffs_staffs_voterposts_show_path(id: voter.id), class: "btn btn-dark mb-2 btn-sm" %>
        </div>
      </div>
    <% end %>
  <% else %>
    <% @voters.each do |voter| %>
      <div class="row">
        <div class="d-flex align-items-center border-top users-index col-4 col-lg-4">
          名前:
        </div>
        <div class="d-flex align-items-center border-top users-index col-6 col-lg-6">
          <%= voter.name %>
        </div>
        <div class="d-flex align-items-center border-top users-index col-2">
          <%= link_to "詳細", staffs_staffs_voterposts_show_path(id: voter.id), class: "btn btn-dark mb-2 btn-sm" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="row">
    <div class="d-flex border-top col-12">
      <%= link_to "戻る", staffs_staffs_toppage_path, class: "btn-gradient confirm-btn" %>
    </div>
  </div>  
</div>

<div id="group-index" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>