config/routes.rb
Rails.application.routes.draw do

  get 'group_email_comments/index'
  get 'group_email_comments/edit'
  devise_scope :voter do
    constraints -> request { request.session[:admin].present? || request.session[:voter_id].present? } do
      root 'voterposts#index', as: :voter_root, constraints: LoggedInConstraint.new("voter") # 投票者としてログインしている場合
      root 'staffs/staffs#toppage', as: :wip_root, constraints: LoggedInConstraint.new("true") # WIPとしてログインしている場合
      root 'staffs/staffs#toppage', as: :other_root, constraints: LoggedInConstraint.new("false") # スポンサー企業としてログインしている場合
    end
    root "voters/registrations#new", as: :public_root
  end

  devise_for :voters, :controllers => {
    :registrations => 'voters/registrations',
    :sessions => 'voters/sessions'
  }

  devise_for :staffs, :controllers => {
    :registrations => 'staffs/registrations',
    :sessions => 'staffs/sessions'
  }

  # 川柳投稿者
  resources :users, only: [:create, :index] do
    collection do
      post :confirm
      get :thanks
    end
  end
  # resources :posts
  
  # 川柳投票
  resources :voterposts do
    resource :likes, only: [:create, :destroy]
  end

  # 管理者・スタッフページ
  namespace :staffs do
    get 'staffs/toppage', to: 'staffs#toppage'
    get 'staffs/index', to: 'staffs#index'
    get 'staffs/users_index', to: 'staffs#users_index'
    get 'staffs/users_graph', to: 'staffs#users_graph'
    get 'staffs/users_show', to: 'staffs#users_show'
    get 'staffs/voterposts_index', to: 'staffs#voterposts_index'
    get 'staffs/voterposts_show', to: 'staffs#voterposts_show'
    post 'staffs/voterposts_index/import', to: 'staffs#import'
    get 'staffs/group_index', to: 'staffs#group_index'
  end

  # adminmessageメール内容変更
  resources :adminmessages
  # 一斉メール  
  resources :group_email_comments do
    member do
      get 'group_email'
    end
  end   
    
  # health_check
  namespace :alb do
    get 'health_check'
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<% if voter_signed_in? || staff_signed_in? %>
  <header>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <span class="navbar-brand nav-title mb-0 h1">ジョカツ川柳</span>
        <button class="navbar-toggler hamburger-icon" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerJokatsu" aria-controls="navbarTogglerJokatsu">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarTogglerJokatsu">
          <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
            <% if voter_signed_in? %>
              <li class="nav-item active nav-link">
                氏名：<%= current_voter.name %>
              </li>  
              <li class="nav-item active nav-link">
                グループ：<%= current_voter.group %>
              </li>
              <li class="nav-item active nav-link">
                <%= link_to 'アカウント編集', edit_voter_registration_path %>
            </li>
              <li class="nav-item active nav-link">
                <%= link_to 'ログアウト', destroy_voter_session_path, method: :delete %>
              </li>
            <% elsif staff_signed_in? %>
              <li class="nav-item active nav-link">
                グループ：<%= current_staff.group_name %>
              </li>
              <% if current_staff.admin == true %>
                <li class="nav-item active nav-link">
                  <%= link_to "川柳投稿者一覧", staffs_staffs_users_index_path %>
                </li>
                <li class="nav-item active nav-link">
                  <%= link_to "審査員・グループ一覧", staffs_staffs_voterposts_index_path %>
                </li>
              <% else %>
              <li class="nav-item active nav-link">
                <%= link_to "審査員一覧", staffs_staffs_voterposts_index_path %>
              </li>
              <% end %>
              <% if current_staff.admin == true %>
                <li class="nav-item active nav-link">
                  <%= link_to "投句完了メール", adminmessages_path(id: current_staff.id) %>
                </li>
                <!--<li class="nav-item active nav-link">
                  <%= link_to "メール一斉送信", group_email_comments_path(id: current_staff.id) %>
                </li>-->
                <li class="nav-item active nav-link">
                  <%= link_to "csv出力（投稿者）", staffs_staffs_index_path(format: :csv, key: :users, group_name: current_staff.group_name), data: { confirm: "CSVを出力します。よろしいですか？" } %>
                </li>
                <li class="nav-item active nav-link">
                  <%= link_to "csv出力（一押し川柳）", staffs_staffs_index_path(format: :csv, key: :voters, group_name: current_staff.group_name), data: { confirm: "CSVを出力します。よろしいですか？" } %>
                </li>
              <% end %>
              <!--<li class="nav-item active nav-link">
                <%= link_to "csv出力（一押し川柳）", staffs_staffs_index_path(format: :csv, key: :voters, group_name: current_staff.group_name), data: { confirm: "CSVを出力します。よろしいですか？" } %>
              </li>-->
              <li class="nav-item active nav-link">
                <%= link_to "csv出力（川柳）", staffs_staffs_index_path(format: :csv, key: :posts, group_name: current_staff.group_name), data: { confirm: "CSVを出力します。よろしいですか？" } %>
              </li>
              <li class="nav-item active nav-link">
                <%= link_to 'ログアウト', destroy_staff_session_path, method: :delete %>
              </li>
            <% end %> 
          </ul>
        </div>
      </div>
    </nav>
  </header> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ジョカツ川柳</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid py-4 <%= devise_controller? ? 'mw-md' : 'mw-xl' %>">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>">
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          <%= msg.html_safe %>
        </div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>